name: Build and Push Docker Image to GCR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
env:
  PROJECT_ID: bespin-mhpark-dev
  IMAGE_NAME: testweb
  IMAGE_TAG: latest
  DOCKERFILE_PATH: ./Dockerfile
  SERVICE_ACCOUNT_EMAIL: git-action@bespin-mhpark-dev.iam.gserviceaccount.com
  
  
jobs:
  build_and_push:
    permissions:
      id-token: write
      contents: read
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: 'actions/checkout@v3'
      
#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

        
    - name: Build Docker image
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
#         token_format: 'access_token'
        create_credentials_file: true
        workload_identity_provider: 'projects/323044112454/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
        service_account: 'git-action@bespin-mhpark-dev.iam.gserviceaccount.com'
        audience: 'https://github.com/chee2e/web_wif'

    - name: Configure Docker client
      run: |
        gcloud auth configure-docker -q
        
    - name: Push Docker image
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
    - id: trivy_scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: json
        exit-code: 0
        output: '${{ env.IMAGE_NAME }}_report.json'
        
    - name: report_processing
      run: |
        cat ${{ env.IMAGE_NAME }}_report.json | jq '.Results[] | {Type, Class, Target, Vulnerabilities: [.Vulnerabilities[] | {PkgName, VulnerabilityID, Severity, InstalledVersion, FixedVersion, Title, PrimaryURL}]}' > ${{ env.IMAGE_NAME }}_result.json
       
        
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '${{ env.IMAGE_NAME }}_result.json'
        destination: 'test-trivy-01/230427'
